modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="upchuck"
displayName="Gourmand"
version="1.0.2"
logoFile = "logo.png"
logoBlur = false
description='''
OMNIEXTRAS WAHOOO
'''

[[dependencies.alienevo_pack]]
modId = "palladium"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alienevo_pack]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
