modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="omni_extras"
displayName="OmniExtras"
version="1.0.5"
logoFile = "logo.png"
logoBlur = false
description='''
an Addonpack that adds more transformations to the Omnitrix
'''

[[dependencies.omni_extras]]
modId = "palladium"
mandatory = true
versionRange = "[1.20.1-4.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.omni_extras]]
modId = "alienevo"
mandatory = true
versionRange = "[1.1.1,)"
ordering = "NONE"
side = "BOTH"
