modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="omni_extras"
displayName="OmniExtras"
version="1.0.4.2"
logoFile = "logo.png"
logoBlur = false
description='''
an Addonpack that adds more transformations to the Omnitrix
'''

[[dependencies.alienevo_pack]]
modId = "palladium"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alienevo_pack]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
